README.md
=> docs(readme): 修改开发步骤

src/components/Meta.js
=> fix: add small tag to icon

src/components/Layout.js, src/components/Meta.js
=> Add edit icon and fix edit link bug

src/components/Layout.js, src/components/doc.js, src/pages/404.js
added a layout option to mark page as not editable
=> fix: 404 page should not be able to edit

README.md
=> docs: add docs for gitpod (#54)

src/components/Tabs.js
一堆 commits 其实都是废的...只给 tab 加了一个 hover 样式，顺便把 `tabs` 更正为 `tab`。（别问，问就是以前的是错的）
=> style: tab hover

docs/test.md, src/pages/tags.js
感觉自定义 CSS 那个操作不太对劲，但是我也不会改了......
Good Luck
=> pref: tags page style

docs/test.md, src/components/Details.js, src/components/Summary.js
1. 修改了高度（其实是右侧 icon 的 padding 改小了），显示效果和主站更接近
2. 尝试滋兹长标题，删掉了 maxheight，改用 margin。。
但是遇到了问题，就是长标题的时候左侧 icon 会变小，原因目前未知
3. 尝试定位展开时 details 向下移动的问题，似乎要修改一个 margin，但还不清楚如何去改它
=> try to update details style

src/components/Meta.js, src/components/NavAndDrawer.js, src/components/Sidebar.js, src/components/Summary.js
=> refactor: sx to usestyles

src/components/NavAndDrawer.js, src/components/Search.js, src/styles/scrollbar.js
=> perf(*): 优化滚动条样式

src/components/Layout.js
=> fix(layout): 解决tags等类型页面没有description的问题

src/pages/tags.js
=> feat(tags): 标签按数量降序排序

src/components/EditWarn.js, src/components/Layout.js, src/components/Meta.js
refactor: 将编辑前须知剥离
feat(meta): 为meta中的开始编辑增加编辑前须知
=> （改良？）编辑前须知

docs/math/poly/fft.md, src/components/AuthorsArray.js, src/components/EditWarn.js, src/components/Link.js, src/components/doc.js
=> update ex links

src/pages/404.js
=> feat: enable comment on 404 pages

src/components/NavAndDrawer.js, src/lib/defaultSettings.ts, src/pages/settings.tsx, src/styles/colors.ts, src/types/settings.ts
WE NEED MORE COLORS!!!!!!
PLEASE FEEL FREE TO ADD MORE
=> feat: appbar theme switcher

src/components/NavAndDrawer.js
=> feat(nav&drawer): change toolbar padding

gatsby-browser.js, src/html.js
=> feat: add google analytics

docs/test.md, gatsby-config.js, package.json, plugins/rehype-pseudocodejs/index.js, plugins/rehype-pseudocodejs/package.json, plugins/rehype-pseudocodejs/pcr.js, plugins/rehype-pseudocodejs/rebind.js, src/theme.js
=> Pseudocode syntax

src/components/NavAndDrawer.tsx, src/components/commentSystem/CommentCard.tsx, src/components/commentSystem/index.tsx, src/lib/defaultSettings.ts
=> 修复了小屏幕按钮过多的问题

gatsby-theme-oi-wiki/src/components/Details.tsx
=> Details: update style

gatsby-theme-oi-wiki/src/components/Search/ResultList.js, gatsby-theme-oi-wiki/src/components/Search/hooks.js, gatsby-theme-oi-wiki/src/components/Search/index.js
几次拆分干了这些事：
1. 把 styles，hooks，API 操作 分别独立出模块
2. 加了一些注释（我理解的
=> Search 组件再拆分

gatsby-theme-oi-wiki/src/pages/pages.js, gatsby-theme-oi-wiki/src/pages/settings.tsx
其中 Settings 改动有点大
- 把 ColorButton 丢到外面去了
- 封装了一个 useSettings 的 hook
=> refactor pages and settings

gatsby-theme-oi-wiki/src/components/NavAndDrawer/index.tsx, gatsby-theme-oi-wiki/src/components/NavAndDrawer/styles.tsx, gatsby-theme-oi-wiki/src/components/Title.tsx, gatsby-theme-oi-wiki/src/pages/settings.tsx, gatsby-theme-oi-wiki/src/theme.js, gatsby-theme-oi-wiki/static/extra.css
改了一些样式上的细节，有点主观因素（因为没找到规范），也许有需要讨论的地方
=> Style adjustment

gatsby-theme-oi-wiki/src/components/Title.tsx
=> fix: 把「作者」改成「贡献者」

gatsby-theme-oi-wiki/src/components/Link/index.js, gatsby-theme-oi-wiki/src/templates/changelog.js
把a标签替换为了自家的Link（open in new tab)
=> update style of changelog

gatsby-theme-oi-wiki/src/theme.js
ref: https://next.oi-wiki.org/contest/problemsetting/
=> update style of blockquote and ol, ul

gatsby-theme-oi-wiki/src/components/Title.tsx
顺便去掉了下划线（因为我发现你ng的链接似乎都是没有下划线的
=> add hover style for author link

gatsby-theme-oi-wiki/src/components/Toc/index.tsx
=> fix: workaround for toc

package.json
https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/yarn
这看起来是 3 个字符，实际上是 10 个字符 🌚️（我把 `y` 用作 yadm 了）
=> build(package.json): add yarn dev

gatsby-theme-oi-wiki/src/components/Layout.js, gatsby-theme-oi-wiki/src/components/Title.tsx
close #685
我自己的想法是去不去掉都行
不去掉：
去掉：
=> feat(?): remove title update time

.github/workflows/build-test.yml, .github/workflows/gh-pages.yml, .github/workflows/lint-check.yml, README.md, example/docs/test.md, gatsby-theme-oi-wiki/gatsby-config.js, gatsby-theme-oi-wiki/package.json, yarn.lock
no more "self-controlled" highlighter :sweat: close #679
=> fix: update shiki to fix latex highlighting.

gatsby-theme-oi-wiki/src/components/EditWarn.tsx, gatsby-theme-oi-wiki/src/components/Footer.js, gatsby-theme-oi-wiki/src/components/Link/index.js, gatsby-theme-oi-wiki/src/components/Meta.tsx, gatsby-theme-oi-wiki/src/components/Title.tsx, gatsby-theme-oi-wiki/src/components/doc.js, gatsby-theme-oi-wiki/src/pages/pages.js, gatsby-theme-oi-wiki/src/templates/changelog.js
=> smartlink!

gatsby-theme-oi-wiki/src/lib/useSetting.tsx, gatsby-theme-oi-wiki/src/pages/settings.tsx, gatsby-theme-oi-wiki/src/theme.js, gatsby-theme-oi-wiki/static/extra.css
note: Fira Mono is the default monospace font of oi-wiki.org
=> fix: remove important for code block

gatsby-theme-oi-wiki/package.json, gatsby-theme-oi-wiki/src/components/Layout.js, gatsby-theme-oi-wiki/src/styles/transition.css, yarn.lock
Add a simple fade-in animation for main content.
=> CSS Transition for main content

gatsby-theme-oi-wiki/src/templates/changelog.js
=> fix(changelog.js): overflow on smaller screens

gatsby-theme-oi-wiki/src/components/Link/index.tsx, gatsby-theme-oi-wiki/src/components/Toc/Toc.tsx, gatsby-theme-oi-wiki/src/components/Toc/index.tsx
* fix scroll to anchor
* refactor the logic of activating toc items to improve the performance
fix #703
=> fix: scroll to anchor

gatsby-theme-oi-wiki/src/components/Comment/Card/ReactionButton.tsx, gatsby-theme-oi-wiki/src/components/Comment/Card/index.tsx, gatsby-theme-oi-wiki/src/components/Comment/Card/styles.ts
=> feat: no color when no reaction & no outline

example/docs/test.md, example/docs/test_code.cpp, example/docs/test_md.md, gatsby-theme-oi-wiki/gatsby-config.js, gatsby-theme-oi-wiki/plugins/gatsby-remark-snippets/index.js, gatsby-theme-oi-wiki/plugins/gatsby-remark-snippets/package.json
=> feat: snippets

gatsby-theme-oi-wiki/static/extra.css
=> fix: missing table style

gatsby-theme-oi-wiki/src/components/Toc/index.tsx
and fix the position where the toc item is activated.
=> feat: modify hash while scrolling

gatsby-theme-oi-wiki/gatsby-config.js, gatsby-theme-oi-wiki/package.json, gatsby-theme-oi-wiki/src/theme/global.ts, gatsby-theme-oi-wiki/src/theme/hightlight-themes/darkplus.ts, gatsby-theme-oi-wiki/src/theme/hightlight-themes/lightplus.ts, gatsby-theme-oi-wiki/src/theme/index.ts, yarn.lock
=> feat: add css variable based code highlighting

gatsby-theme-oi-wiki/src/components/Seo.tsx
ouuan, [07.09.21 10:22]
next 竟然被 Google 收录了
mgt, [07.09.21 10:23]
这下坏了
ouuan, [07.09.21 10:23]
要不要考虑写 canonical link
mgt, [07.09.21 10:23]
我觉得有必要
=> feat: add canonical link

gatsby-theme-oi-wiki/src/theme/global.ts
=> add: anchor link 黑暗模式下自动变色
